### ISSUE TITLE
Do the values make sense on a AMD/Desktop?

### ISSUE THREAD

**Issue by skjerns** [kphanipavan/cpu-power-monitor#4]
I'm running a desktop with an AMD 3900X. The widget does display power values that do seem realistic, at least for CPU usage.

However, I know that measuring power consumption on Desktop CPUs is notoriously tricky.

Do the values of the widget have any meaning on my system? Or can I disregard them as nonsense?

**Comment by aviallon** [comment]
@skjerns I bet this widget uses Intel RAPL, which is actually implemented for AMD CPUs (Zen 2 and later, at least).
So yeah, the values reported do make sense.

**Comment by kphanipavan** [comment]
Yes. This widget indeed uses the RAPL interface to get the energy usage of the processor, as mentioned by @aviallon. This widget works with AMD CPUs.

LMK if it doesn't work. Closing for now.

**Comment by clst** [comment]
Small Update: It works fine and displays the correct values on my AMD Ryzen 3600X with kernel 6.14 out of the box (so does `powerstat` in RAPL mode).

Once the kernel module zenergy is loaded https://github.com/boukehaarsma23/zenergy you can also get a sensor but that is only needed for something like mangoHUD.
