### ISSUE TITLE
Take some kind of average over time?

### ISSUE THREAD

**Issue by julianbarg** [kphanipavan/cpu-power-monitor#6]
I installed this alongside power-monitor because I was curious how much my CPU usage contributes to battery usage. Unfortunately, cpu power usage is pretty noisy while battery usage is quite stable. Would be neat to have an alt mode that takes a measurement maybe every 0.1s and averages that out over a second or so.

**Comment by kphanipavan** [comment]
Hello @julianbarg 

I appreciate the feedback. Although smooth data output is desirable, it is not technically possible in this case. The wattage numbers are not directly available in a file to read from, they have to be calculated using the energy usage counter data available at `/sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/energy_uj`. So if the CPU does any intensive task for a split second, that gets reflected in the energy usage, which then shows up as spiked power, no matter how you calculate it (1 second at a time or 10 power values taken in one second and averaged).

If a smooth change in number is very necessary, a moving average calculation can be setup, where the last `n` values can be stored and averaged upon, resulting in a gradual change of power number. Although it changes gradually, the values you are shown in this case are not strictly accurate, having exact calculation can help you debug certain cenarios.

~ Pvn

**Comment by kphanipavan** [comment]
Closing for now. Reopen if necessary
