### ISSUE TITLE
Plasma 6 support

### ISSUE THREAD

**Issue by NucleaPeon** [kphanipavan/cpu-power-monitor#8]
I see you are already working on plasma 6 compatibility, which is greatly appreciated. I recently updated to Plasma 6 and the monitor stopped working. 

Please close this issue when that is done, so I can be notified that it's ready. :)
Thank you.

**Comment by kphanipavan** [comment]
Just pushed an update. Rewrote the plugin for Plasma 6. Also pushed an update to kde plugin store. LMK if it doesn't work. 

Appreciate the appreciations

~Pvn

**Comment by NucleaPeon** [comment]
Just installed it via the plasma store. Works great, only weird thing was that the update interval defaulted to 0.1s. Great to have it back!
